In [1]:
import numpy as np

In [2]:
# vetor
a1 = np.array([1, 2, 3])

# matrix de duas dimensões
a2 = np.array([[4, 5, 6],
               [7, 8, 9]])

# matrix
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
                [[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]]])

In [3]:
a1.shape

(3,)

In [4]:
a1.ndim, a2.ndim

(1, 2)

In [5]:
a3.size

18

In [6]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [7]:
a1

array([1, 2, 3])

In [8]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [9]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

## Criando arrays

In [10]:
array_simples = np.array([1, 2, 3])
array_simples

array([1, 2, 3])

In [11]:
ones = np.ones((10, 2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
zeros = np.zeros((4, 4, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
range_a1 = np.arange(0, 10, 2)
range_a1

array([0, 2, 4, 6, 8])

In [14]:
random_1 = np.random.randint(10, size=(5, 3))
random_1

array([[0, 2, 9],
       [3, 1, 7],
       [4, 3, 7],
       [1, 8, 2],
       [1, 8, 7]])

In [15]:
random_2 = np.random.random((5, 3))
random_2

array([[0.89890544, 0.88582479, 0.33857118],
       [0.263466  , 0.84783358, 0.12396366],
       [0.97984958, 0.37468796, 0.67840056],
       [0.09422167, 0.92172837, 0.39545067],
       [0.73629198, 0.48244255, 0.78658796]])

In [16]:
np.random.seed(42)
np.random.randint(10, size=(5, 3))

array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

## Acessando e visualizando os elementos

In [17]:
a1

array([1, 2, 3])

In [18]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [19]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [20]:
a1[0]

1

In [21]:
a2[0,0]

4

In [22]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

## Aritmética

In [23]:
a1

array([1, 2, 3])

In [24]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [25]:
a1 + ones

array([2., 3., 4.])

In [26]:
a1 - ones

array([0., 1., 2.])

In [27]:
a1 * ones

array([1., 2., 3.])

In [28]:
a1 / ones

array([1., 2., 3.])

In [29]:
a2 // a1

array([[4, 2, 2],
       [7, 4, 3]])

In [30]:
a1 ** 2

array([1, 4, 9])

In [31]:
np.square(a1)

array([1, 4, 9])

In [32]:
a1 % 2

array([1, 0, 1])

In [33]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

In [34]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

## Agregação

In [35]:
sum(a1)

6

In [36]:
np.sum(a1)

6

In [37]:
grande_array = np.random.random(1000000)
grande_array.size

1000000

In [38]:
%timeit sum(grande_array) # Python sum()
%timeit np.sum(grande_array) # NumPy np.sum()

1 loop, best of 5: 166 ms per loop
The slowest run took 4.53 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 390 µs per loop


In [39]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [40]:
np.mean(a2)

6.5

In [41]:
np.max(a2)

9

In [42]:
np.min(a2)

4

In [43]:
np.std(a2)

1.707825127659933

In [44]:
np.var(a2)

2.9166666666666665

## Reshaping e Transpose

In [45]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [46]:
a2.shape

(2, 3)

In [47]:
a2 + a3

ValueError: ignored

In [48]:
a2.reshape(2, 3, 1)

array([[[4],
        [5],
        [6]],

       [[7],
        [8],
        [9]]])

In [49]:
a2.reshape(2, 3, 1) + a3

array([[[ 5,  6,  7],
        [ 9, 10, 11],
        [13, 14, 15]],

       [[17, 18, 19],
        [21, 22, 23],
        [25, 26, 27]]])

In [50]:
a2.T

array([[4, 7],
       [5, 8],
       [6, 9]])

In [51]:
a2.shape

(2, 3)

In [52]:
a2.T.shape

(3, 2)

## Operadores de comparação e ordenação de arrays

In [53]:
a1

array([1, 2, 3])

In [54]:
a2

array([[4, 5, 6],
       [7, 8, 9]])

In [55]:
a1 > a2

array([[False, False, False],
       [False, False, False]])

In [56]:
a1 <= a2

array([[ True,  True,  True],
       [ True,  True,  True]])

In [57]:
a1 > 5

array([False, False, False])

In [58]:
a1 == a1

array([ True,  True,  True])

In [59]:
a1 == a2

array([[False, False, False],
       [False, False, False]])

In [60]:
random_1

array([[0, 2, 9],
       [3, 1, 7],
       [4, 3, 7],
       [1, 8, 2],
       [1, 8, 7]])

In [61]:
np.sort(random_1)

array([[0, 2, 9],
       [1, 3, 7],
       [3, 4, 7],
       [1, 2, 8],
       [1, 7, 8]])

In [62]:
np.argsort(a1)

array([0, 1, 2])

In [63]:
np.argmin(a1)

0